In [7]:
import numpy as np
a = np.array([[1,2]])
#a = np.array([a])
a = np.atleast_3d(a)
print(a)
print(a.shape)

[[[1]
  [2]]]
(1, 2, 1)


In [11]:
import numpy as np
a = np.zeros([2,3],dtype=np.int_)
print(np.expand_dims(a,axis = 0).shape)

(1, 2, 3)


In [9]:
import numpy as np
x = np.zeros([2,3])
print(np.atleast_3d(x).shape)

(2, 3, 1)


In [19]:
import numpy as np
x = np.zeros([2,3,3])
print(np.squeeze(a).shape)

(2, 3)


In [28]:
import numpy as np
a = np.zeros(3)
b = np.ones(3)
c = np.concatenate((a,b),0)
c = np.c_[a,b]
print(c)

[[0. 1.]
 [0. 1.]
 [0. 1.]]


In [32]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
c = np.column_stack((a,b))
d = np.array([a,b])
print(d)
print(c)

[[1 2 3]
 [2 3 4]]
[[1 2]
 [2 3]
 [3 4]]


In [40]:
import numpy as np
x = np.arange(1,15)
print('初始矩阵:',x)
print('拆分后')
print(np.split(x,[2,6]))

初始矩阵: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
拆分后
[array([1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13, 14])]


In [51]:
import numpy as np
a = np.array([1,2,2,4,0,0,0,0,3,0])
c = a==2
print(a==2)
print(c+a)
print(c+c)
idx = np.nonzero(a==2)
b = np.nonzero(a)
print(a[idx])
print(b)

[False  True  True False False False False False False False]
[1 3 3 4 0 0 0 0 3 0]
[False  True  True False False False False False False False]
[2 2]
(array([0, 1, 2, 3, 8], dtype=int64),)


In [52]:
import numpy as np
a = np.arange(10).reshape(5,2)
print(a)
np.sum(a,axis=0)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


array([20, 25])

In [57]:
import numpy as np
a = np.arange(10).reshape(5,2)
print(a)
print(np.nonzero(a))
idx,jdx = np.nonzero(a)
for i in range(len(jdx)):
    print(a[idx[i], jdx[i]])

print(a[idx,jdx])

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
(array([0, 1, 1, 2, 2, 3, 3, 4, 4], dtype=int64), array([1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int64))
1
2
3
4
5
6
7
8
9
[1 2 3 4 5 6 7 8 9]


In [64]:
import numpy as np
a = np.array([1,2,3,4,5,6,7])
b = 8
c = np.array([3,5])
print(np.isin(b,a))
print(np.isin(c,a))
print(3 in a)

False
[ True  True]
True


In [67]:
import numpy as np
a = np.linspace(0,1,10)
b = np.arange(0,1,0.1)
c = np.arange(0,1,0.6)
print(a)
print(b)
print(c)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0.  0.6]


In [72]:
import numpy as np
x = np.zeros(10)
x.flags.writeable = False
x[3] = 100

ValueError: assignment destination is read-only

In [75]:
import numpy as np
a = np.arange(100)
c = (a%3==0)|(a%5==0)
print(c)
print(np.nonzero(c))

[ True False False  True False  True  True False False  True  True False
  True False False  True False False  True False  True  True False False
  True  True False  True False False  True False False  True False  True
  True False False  True  True False  True False False  True False False
  True False  True  True False False  True  True False  True False False
  True False False  True False  True  True False False  True  True False
  True False False  True False False  True False  True  True False False
  True  True False  True False False  True False False  True False  True
  True False False  True]
(array([ 0,  3,  5,  6,  9, 10, 12, 15, 18, 20, 21, 24, 25, 27, 30, 33, 35,
       36, 39, 40, 42, 45, 48, 50, 51, 54, 55, 57, 60, 63, 65, 66, 69, 70,
       72, 75, 78, 80, 81, 84, 85, 87, 90, 93, 95, 96, 99], dtype=int64),)


In [82]:
import numpy as np
a = np.zeros(10)
c = np.arange(10,dtype=np.bool_)
print(c)

ValueError: no fill-function for data-type.

In [77]:
import numpy as np
x = np.arange(1e3)
print(x)

[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.
  14.  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.
  28.  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.
  42.  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.
  56.  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.
  70.  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.
  84.  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.
  98.  99. 100. 101. 102. 103. 104. 105. 106. 107. 108. 109. 110. 111.
 112. 113. 114. 115. 116. 117. 118. 119. 120. 121. 122. 123. 124. 125.
 126. 127. 128. 129. 130. 131. 132. 133. 134. 135. 136. 137. 138. 139.
 140. 141. 142. 143. 144. 145. 146. 147. 148. 149. 150. 151. 152. 153.
 154. 155. 156. 157. 158. 159. 160. 161. 162. 163. 164. 165. 166. 167.
 168. 169. 170. 171. 172. 173. 174. 175. 176. 177. 178. 179. 180. 181.
 182. 183. 184. 185. 186. 187. 188. 189. 190. 191. 192. 193. 194. 195.
 196. 